### ISSUE TITLE
文件标题栏显示重叠

### ISSUE THREAD

**Issue by itachaaa** [chenshinshi/OneNote#13]
![图片](https://github.com/user-attachments/assets/9b896f84-1251-4a00-bfcf-c70af58555a5)
貌似标题长了之后，图标会合图标重叠到一起

**Comment by StupidYR** [comment]
+1

**Comment by StupidYR** [comment]
折腾了一下，有一个不太成熟的解决办法：

在 `工作空间/conf/appearance/themes/OneNote/style/02-appearance/tab-bar.css` 文件中 注释掉以下两行代码，即可修复标签页内图标与文字重叠的问题：

```css
.layout-tab-bar .item__icon {
margin-right:-24px}
```
